name: Static Analysis

on: pull_request

permissions:
  contents: read

env:
  COMPOSER_NO_INTERACTION: 1

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    name: PHP-CS-Fixer

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 7.4
          coverage: none

      - name: Install PHP-CS-Fixer
        run: composer install --working-dir=tools/php-cs-fixer

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer check -v --show-progress=dots --stop-on-violation --using-cache=no

  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 7.4
          coverage: none

      - name: Install PHPStan
        run: composer install --working-dir=tools/phpstan

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
